### PR TITLE
Fix formfield cursor behaviour

### LINKED ISSUE #718: Cursor jumps to end of textfield
Has superficial similarity to https://github.com/subconsciousnetwork/subconscious/issues/667.

In some text fields adding or removing a character in the middle of the string will jump the cursor to the end. This is most obvious when editing a long textfield such as a DID input, gateway URL or the profile bio field. 

It seems like this is due to mutating the value of the text field (perhaps via validation) and blowing away the selection context as a result? We need a simplified example to reproduce it.

Specifically, we should compare @State / ObservableStore against TextField / ValidatedTextField. I doubt that all TextFields are broken on iOS so something must be wrong in one of the 2x2 quadrants here.

### PR DESCRIPTION
**Pull request by bfollington**
Fixes #718 
Fixes https://github.com/subconsciousnetwork/subconscious/issues/708
Fixes https://github.com/subconsciousnetwork/subconscious/issues/674

# Changes

- `ValidatedTextField` has an internal `@State var` that holds the current field value
    - Edits are replayed to the store to keep the two in sync
- New `ValidatedFormField` component which wraps `ValidatedTextField` wires up everything to talk to a backing `FormField<>`
- Replaced all fields by `FormField`s
- Nickname can be entered with capitals but will always persist and present in lowercase
- Bio will automatically truncate >280 chars
- Clarified profile memo lifecycle

### CODE REVIEW

File: xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift [hunk 1]
```diff
@@ -7,17 +7,57 @@
...
 
 /// A text field that comes with help text and a validation flag
 struct ValidatedTextField: View {
+    @State var innerText: String = ""
+    
     var alignment: HorizontalAlignment = .leading
     var placeholder: String
     @Binding var text: String
     var onFocusChanged: (Bool) -> Void = { _ in}
+    var onTextChanged: () -> Void = {}
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift:56]: Drop this

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 2]
```diff
@@ -104,7 +106,7 @@ enum AppAction: CustomLogStringConvertible {
     /// Set sphere/user nickname
     /// Sets form field, and persists if needed.
     case setNickname(_ nickname: String)
-    case persistNickname(_ nickname: String)
+    case submitNickname(_ nickname: Petname.Name)
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/AppView.swift:109]: Updated to more clearly reflect how it's being used, mirrors the way GatewayURL is managed

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 3]
```diff
@@ -929,32 +955,29 @@ struct AppModel: ModelProtocol {
...
-            logger.log("Nickname saved: \(validated)")
-            
-            return update(
-                state: model,
-                action: .updateOurProfileWithNickname(validated),
-                environment: environment
-            )
-        }
+        var model = state
+        model.nickname = nickname.description
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/AppView.swift:970]: We store the lowercase version of the nickname

File: xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift [hunk 4]
```diff
@@ -7,17 +7,56 @@
...
+    
     var alignment: HorizontalAlignment = .leading
     var placeholder: String
     @Binding var text: String
     var onFocusChanged: (Bool) -> Void = { _ in}
     var caption: String
-    var hasError: Bool = false
     var axis: Axis = .horizontal
     var autoFocus: Bool = false
+    var isValid: Bool = true
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift:59]: I changed this back to `isValid` and renamed the concept of `hasError` to `shouldPresentAsInvalid` in `FormField`.

File: xcode/Subconscious/Shared/Models/FormField.swift [hunk 5]
```diff
@@ -27,8 +27,8 @@ struct FormField<Input: Equatable, Output>: ModelProtocol {
     static func == (lhs: FormField<Input, Output>, rhs: FormField<Input, Output>) -> Bool {
         return (
             lhs.value == rhs.value &&
+            lhs.defaultValue == rhs.defaultValue &&
             lhs.touched == rhs.touched &&
-            lhs.isValid == rhs.isValid &&
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Models/FormField.swift:31]: No point checking a derived property for equality.

File: xcode/Subconscious/SubconsciousTests/Tests_App.swift [hunk 6]
```diff
@@ -66,8 +62,8 @@ final class Tests_App: XCTestCase {
         )
         XCTAssertEqual(b.state.nicknameFormField.value, "valid", "Nickname form field is set")
         XCTAssertEqual(b.state.nicknameFormField.isValid, true, "Nickname form field is valid")
-        XCTAssertEqual(b.state.nicknameFormFieldValue, "valid", "Nickname form field value set")
-        XCTAssertEqual(b.state.isNicknameFormFieldValid, true, "Nickname form field is valid")
-        XCTAssertEqual(b.state.nickname, "valid", "Nickname is saved, because form field value is valid")
+        
+        let c = AppModel.update(state: model, action: .submitNickname(Petname.Name("valid")!), environment: AppEnvironment())
+        XCTAssertEqual(c.state.nickname, "valid", "Nickname is saved after submitted valid nickname.")
```
Comment (bfollington) [inline xcode/Subconscious/SubconsciousTests/Tests_App.swift:67]: Updated to capture new behaviour: `state.nickname` won't be update until `submitNickname` is called with a valid name.

File: xcode/Subconscious/Shared/Components/Settings/ProfileSettingsView.swift [hunk 7]
```diff
@@ -10,23 +10,27 @@ import ObservableStore
...
-                    ),
-                    caption: "Lowercase letters, numbers, and dashes only",
-                    hasError: !app.state.isNicknameFormFieldValid
+                    field: app.state.nicknameFormField,
+                    send: app.send,
+                    tag: AppAction.nicknameFormField,
+                    caption: "Lowercase letters, numbers and dashes only."
                 )
-                .formField()
+                .textInputAutocapitalization(.never)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Settings/ProfileSettingsView.swift:24]: 🥳

File: xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift [hunk 8]
```diff
@@ -7,17 +7,56 @@
 
 import SwiftUI
 import Combine
+import ObservableStore
+
+struct ValidatedFormField<T: Equatable, Action>: View {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift:12]: This wrapping view feels strange to me. Can we do it with one view?

File: xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift [hunk 9]
```diff
@@ -7,17 +7,56 @@
...
+            submitLabel: submitLabel,
+            onSubmit: onSubmit
+        )
+        .formField()
+    }
+}
 
 /// A text field that comes with help text and a validation flag
 struct ValidatedTextField: View {
+    @State var innerText: String = ""
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift:50]: State should be `private`

File: xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift [hunk 10]
```diff
@@ -7,17 +7,56 @@
...
 import SwiftUI
 import Combine
+import ObservableStore
+
+struct ValidatedFormField<T: Equatable, Action>: View {
+    var alignment: HorizontalAlignment = .leading
+    var placeholder: String
+    var field: FormField<String, T>
+    var send: (Action) -> Void
+    var tag: (FormFieldAction<String>) -> Action
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift:17]: I would like to avoid passing down tagging functions, and instead pass down a tagged `send` function. The tagging function is an implementation detail the child shouldn't know about, and we don't want the child to be able to pass up anything except its own actions.

Eventually this tagging pattern will be replaced by `StoreProtocol.viewStore` helper https://github.com/subconsciousnetwork/ObservableStore/blob/main/Sources/ObservableStore/ObservableStore.swift#LL347C17-L347C26

**Comment by gordonbrander** [comment]
It would also be worth investigating why this happens for this component, but not other input fields that are driven by ObservableStore. 

One noted difference is the closure in this model. I wonder if it might be confusing SwiftUI's change detection under the hood.

File: xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift (hunk 8 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift:12]: Yep, I was preserving the path to using the prior API but you're right, I can just flatten this out since we always use this new form.

**Comment by bfollington** [comment]
> It would also be worth investigating why this happens for this component, but not other input fields that are driven by ObservableStore.
> 
> One noted difference is the closure in this model. I wonder if it might be confusing SwiftUI's change detection under the hood.

I think there was a little bit of a red herring here, thought I'm still not 100% sure. Based on my testing here is my understanding:

I _think_ that the fundamental cause of the cursor issues is a race condition between updating the binding via the store and internal input events of the TextField. It seemed like `FormField`s were experience _more_ cursor issues but I saw (and have seen) the same issues crop up in other fields. I recall the first report I heard of this problem was the Gateway URL field, which did not use the `FormField` abstraction until this PR.

After decoupling the input binding from the store the cursor issues resolved, but I was seeing stale validation results instead. To fix that I introduced the `ValidatedFormField` API that takes the entire `FormField` struct as a property (as opposed to the current value and a computed `hasError` property). I suspected that the change detection would be more reliable checking struct equality vs. a computed field and it appears to behave correctly now, though I'll admit I am hand waving.

(Sidenote: sheets made no difference to anything)

File: xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift (hunk 10 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift:17]: I'm not sure why I blanked on the fact we already have `Address.forward`. I switched everything to use that instead.

File: xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift [hunk 11]
```diff
@@ -7,21 +7,21 @@
 
 import SwiftUI
 import Combine
+import ObservableStore
 
-/// A text field that comes with help text and a validation flag
-struct ValidatedTextField: View {
+struct ValidatedFormField<T: Equatable>: View {
+    @State private var innerText: String = ""
+    @FocusState private var focused: Bool
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift:14]: I like the way we've wrapped this up. It's unfortunate that we have to replay changes, but the way we're doing it makes it an invisible implementation detail of the view. 👍

**Review by gordonbrander — APPROVED** [review]
LGTM!

Thank you for this. Form input and focus bugs are often one of the trickiest aspects of UI frameworks.
