### PR TITLE
Fix Omnibox icon for various states

### LINKED ISSUE #541: Omnibox incorrectly shows profile icon sometimes
For local content:

For sphere content (shows correctly, but is incorrect after opening sheet):

### PR DESCRIPTION
**Pull request by gordonbrander**
Fixes #541.

Also simplifying display style of location in bar. My sense is that petname parts should all have the same weight/color treatment, since they make up the "trust domain". This mirrors similar UI in browsers:

Screenshot 2023-04-25 at 3 33 08 PM

### CODE REVIEW

File: xcode/Subconscious/Shared/Components/Common/Byline/PetnameBylineView.swift [hunk 1]
```diff
@@ -33,12 +31,12 @@ struct PetnameBylineView: View {
...
                 // Particular structure to ensure truncation trims the path and never the name
                 Text(".\(rest)")
-                    .foregroundColor(.secondary)
                     .font(.callout)
-                    .fontWeight(.regular)
                     .lineLimit(1)
             }
         }
+        .fontWeight(.medium)
+        .foregroundColor(petnameColor)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Byline/PetnameBylineView.swift:39]: Treat all parts of the petname with the same color/weight treatment.

File: xcode/Subconscious/Shared/AppIcon.swift [hunk 2]
```diff
@@ -18,7 +18,7 @@ extension AppIcon {
     var systemName: String {
         switch (self) {
         case .you:
-            return "face.smiling.inverse"
+            return "face.smiling"
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/AppIcon.swift:21]: Use outline style for all Omnibox icons.

Comment (gordonbrander) [reply xcode/Subconscious/Shared/AppIcon.swift]: Fixed

File: xcode/Subconscious/Shared/AppIcon.swift [hunk 3]
```diff
@@ -8,7 +8,7 @@
 import SwiftUI
 
 enum AppIcon {
-    case you
+    case you(ColorScheme)
```
Comment (bfollington) [inline xcode/Subconscious/Shared/AppIcon.swift:11]: I started going down a rabbithole of picking new icons and realised it's not **that** much work to pick the right smiley. We're not the only ones to hit this issue and fix it this way: https://github.com/Dimillian/IceCubesApp/issues/1193

**Review by bfollington — APPROVED** [review]
I went ahead and made the smiley icon parameterised by color scheme
