### PR TITLE
Restore full-document attribute rendering

### LINKED ISSUE #431: Tapping slashlinks in editor does nothing
This is a recent regression.

# Reproduction

1. Create a note
2. Add a `/slashlink` to the body
3. Try and tap it

# Expected Behaviour

Tapping a link navigates to the note it references.

### PR DESCRIPTION
**Pull request by bfollington**
This renders attributes directly to TextStorage (like we used to but with TK2) to resolve #431

- [x] Restore old functionality
- [x] Remove per-fragment rendering (otherwise we're doing it twice)

I've also put together a proof-of-concept for how we could do per-paragraph rendering in #433

### CODE REVIEW

File: xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift [hunk 1]
```diff
@@ -164,38 +164,55 @@ struct SubtextTextViewRepresentable: UIViewRepresentable {
...
-    class Coordinator: NSObject, UITextViewDelegate, NSTextContentStorageDelegate, NSTextContentManagerDelegate, NSTextLayoutManagerDelegate {
+    class Coordinator: NSObject, UITextViewDelegate, NSTextContentStorageDelegate, NSTextStorageDelegate, NSTextContentManagerDelegate, NSTextLayoutManagerDelegate {
         /// Is event happening during updateUIView?
         /// Used to avoid setting properties in events during view updates, as
         /// that would cause feedback cycles where an update triggers an event,
         /// which triggers an update, which triggers an event, etc.
         var isUIViewUpdating: Bool
         var representable: SubtextTextViewRepresentable
         var renderTranscludeBlocks: Bool = false
+        var subtext: Subtext? = nil
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift:176]: I'm caching the parse results so we can use them to detect transclude blocks without repeating work.

File: xcode/Subconscious/Shared/Library/NSRangeUtilities.swift [hunk 2]
```diff
@@ -14,3 +15,26 @@ extension NSRange {
         return range != nil
     }
 }
+
+
+// https://gist.github.com/krzyzanowskim/057676af670f06fa6061473ac28a6c58
+extension NSRange {
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Library/NSRangeUtilities.swift:21]: No license on this gist :( but it's incredibly useful

File: xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift [hunk 3]
```diff
@@ -164,38 +164,55 @@ struct SubtextTextViewRepresentable: UIViewRepresentable {
...
+        func textStorage(
+          _ textStorage: NSTextStorage,
+          willProcessEditing: NSTextStorage.EditActions,
+          range: NSRange,
+          changeInLength: Int
+        ) {
+            SubtextTextViewRepresentable.logger.debug(
+              "textStorage: render markup attributes"
+            )
+            textStorage.setAttributes(
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift:204]: What is this code doing (`textStorage.setAttributes`)

File: xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift [hunk 4]
```diff
@@ -164,38 +164,55 @@ struct SubtextTextViewRepresentable: UIViewRepresentable {
...
-                url: SubtextTextViewRepresentable.toSubURL
-            )
-            self.subtext = subtext
-            super.init(attributedString: renderedAttributedString)
-        }
-    }
-
     //  MARK: Coordinator
-    class Coordinator: NSObject, UITextViewDelegate, NSTextContentStorageDelegate, NSTextContentManagerDelegate, NSTextLayoutManagerDelegate {
+    class Coordinator: NSObject, UITextViewDelegate, NSTextContentStorageDelegate, NSTextStorageDelegate, NSTextContentManagerDelegate, NSTextLayoutManagerDelegate {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift:168]: Nit: let's wrap this long line. https://google.github.io/swift/#type-and-extension-declarations

File: xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift (hunk 3 above)
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift:204]: What is this code doing (textStorage.setAttributes)?

File: xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift [hunk 5]
```diff
@@ -299,18 +318,6 @@ struct SubtextTextViewRepresentable: UIViewRepresentable {
 
             return layoutFragment
         }
-        
-        // MARK: - NSTextContentStorageDelegate
-        
-        func textContentStorage(_ textContentStorage: NSTextContentStorage, textParagraphWith range: NSRange) -> NSTextParagraph? {
-            guard let attributedSubstring = textContentStorage.textStorage?
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift:306]: Did the API change in TK2? This form would mean we don't need to bring in the NSRange extension.

File: xcode/Subconscious/Shared/Library/NSRangeUtilities.swift (hunk 2 above)
Comment (gordonbrander) [reply xcode/Subconscious/Shared/Library/NSRangeUtilities.swift:21]: If no license, then we must write our own.

File: xcode/Subconscious/Shared/Parsers/Subtext.swift [hunk 6]
```diff
@@ -722,3 +724,21 @@ extension Subtext {
         return shortlinkFor(index: range.lowerBound)
     }
 }
+
+extension Subtext {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Parsers/Subtext.swift:728]: Would prefer to add this extension in the SubtextTextEditor file. That way SubtextTextEditor knows about Subtext and NSTextParagraph, but Subtext doesn't have to know about NSTextParagraph.

**Review by gordonbrander — CHANGES_REQUESTED** [review]
A few questions and clarifications on how this is working

File: xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift (hunk 3 above)
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift:204]: If I understand correctly, this is clearing all attributes from string.

I think we should always clear all attributes from string before rendering new attributes with `renderAttributesOf`.

Let's move this to `Subtext.renderAttributesOf`.

**Review by gordonbrander — CHANGES_REQUESTED** [review]

File: xcode/Subconscious/Shared/Parsers/Subtext.swift [hunk 7]
```diff
@@ -722,3 +724,21 @@ extension Subtext {
...
+                return false
+            }
+            guard let tcm = forParagraph.textContentManager else {
+                return false
+            }
+            
+            guard let range: Range<String.Index> = Range(NSRange(contentRange, in: tcm), in: base) else {
+                return false
+            }
+            return b.body().range.overlaps(range)
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Parsers/Subtext.swift:741]: Let's check that subtext is using the same underlying strings as textContentManager

File: xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift (hunk 3 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift]: This is the way it _used_ to work before we moved to TK2. Regardless, I've moved this into `renderAttributesOf` now.

**Review by gordonbrander — APPROVED** [review]
