### PR TITLE
Use Config.noosphere.ownerKeyName constant

### LINKED ISSUE #540: Error: No value found for 'user_key_name'
Ran into this after an XCode update.

The bug prevents saving new content to sphere.

```log
2023-04-25 11:28:31.899351-0400 Subconscious[68065:2183800] [NoosphereService] init Sphere with identity: did:key:z6Mku9WrreHFyg6f4sHHWgtu4nrCHorqk8VBqjrceiZZzscr
2023-04-25 11:28:31.899476-0400 Subconscious[68065:2182292] [detail] [action] failSave(address: public::/hmm, message: "Foreign Error: No value found for \'user_key_name\'")
2023-04-25 11:28:31.899546-0400 Subconscious[68065:2182292] [detail] Save failed for entry (public::/hmm) with error: Foreign Error: No value found for 'user_key_name'
2023-04-25 11:28:31.900257-0400 Subconscious[68065:2182292] [SubtextTextViewRepresentable] updateUIView
2023-04-25 11:28:31.904535-0400 Subconscious[68065:2182292] [detail] [action] failSave(address: public::/hmm, message: "Foreign Error: No value found for \'user_key_name\'")
2023-04-25 11:28:31.904607-0400 Subconscious[68065:2182292] [detail] Save failed for entry (public::/hmm) with error: Foreign Error: No value found for 'user_key_name'
2023-04-25 11:28:32.365548-0400 Subconscious[68065:2182292] [notebook] [action] setDetails([])
```

### PR DESCRIPTION
**Pull request by gordonbrander**
...instead of user-provided nickname, when designating an owner key name. This value is not network-facing, and just needs to be something constistent across runs. Hard-coding avoids user input errors for value, and also avoids having to track changes to owner key name.

Fixes #540.

### CODE REVIEW

File: xcode/Subconscious/Shared/Services/AppDefaults.swift [hunk 1]
```diff
@@ -15,9 +15,6 @@ struct AppDefaults {
     @UserDefaultsProperty(forKey: "isNoosphereEnabled")
     var isNoosphereEnabled = false
 
-    @UserDefaultsProperty(forKey: "ownerKeyName")
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/AppDefaults.swift:18]: No longer needed

File: xcode/Subconscious/Shared/Services/DataService.swift [hunk 2]
```diff
@@ -78,7 +78,6 @@ actor DataService {
         // Instead, we return the receipt so that mnemonic can be displayed
         // and discarded.
         AppDefaults.standard.sphereIdentity = sphereReceipt.identity
-        AppDefaults.standard.ownerKeyName = ownerKeyName
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/DataService.swift:81]: No longer needed

File: xcode/Subconscious/Shared/Services/DatabaseService.swift [hunk 3]
```diff
@@ -25,7 +25,6 @@ struct DatabaseMigrationInfo: Hashable {
 enum DatabaseMetaKeys: String {
     case sphereIdentity = "sphere_identity"
     case sphereVersion = "sphere_version"
-    case ownerKeyName = "owner_key_name"
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/DatabaseService.swift:28]: No longer used or needed

File: xcode/Subconscious/Shared/Config.swift [hunk 4]
```diff
@@ -56,7 +56,7 @@ struct NoosphereConfig: Equatable, Codable {
     /// NOTE: In future, we might support multiple spheres. If so, this
     /// flag will be deprecated in favor of multiple spheres
     var sphereStoragePath = "sphere"
-    /// Default owner key name for spheres on this device
-    var ownerKeyName = "User"
+    /// Owner key name for key that owns default sphere on this device.
+    var ownerKeyName = "Subconscious"
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Config.swift:60]: I imagine for Touch ID, we may end up seeing sheets that say something like "Such-and-such wants to access [owner key name]".

Given we do talk about "your Subconscious", I think calling the default sphere owner key "Subconscious" makes a lot of sense. "Such-and-such wants to access Subconscious"

**Review by cdata — APPROVED** [review]
LGTM!
