### PR TITLE
Fix memory santization error

### LINKED ISSUE #759: `error.pointee` sometimes has incorrect value
I believe that I've accidentally discovered a memory bug in the app. I stumbled across these diagnostics in Xcode today (under Scheme Settings) and thought I'd try them out. Docs are here for the different options: https://developer.apple.com/library/archive/documentation/Performance/Conceptual/ManagingMemory/Articles/MallocDebug.html

Long story short: the app crashes under `Address Sanitization` and/or `Malloc Scribble` right here: https://github.com/subconsciousnetwork/subconscious/blob/2bc417c1a0838e2585a1475813f56de2d49dc8ff/xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift#L255

Thanks to the using `MallocPreScribble` and `MallocScribble` I can see that (sometimes?) `error.pointee` is a pointer to a garbage address. `MallocPreScribble` writes `0xAA` to any newly allocated bytes and my value for `error.pointee` is `.some(0xaaaaaaaaaaaaaaaa)`.

This _seems_ like we're allocating the space for the pointer but not actually writing to it on the NS side?

### PR DESCRIPTION
**Pull request by bfollington**
Fixes #759 

Discovered using the `Address Sanitizer` diagnostic in Xcode, which I've left enabled in Debug.

We must explicitly zero-out the `pointee` field after this unsafe allocation, otherwise it could literally be pointing _anywhere_.

### CODE REVIEW

File: xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift [hunk 1]
```diff
@@ -244,6 +244,9 @@ public actor Noosphere {
         _ perform: (UnsafeMutablePointer<OpaquePointer?>) -> Z
     ) throws -> Z {
         let error = UnsafeMutablePointer<OpaquePointer?>.allocate(capacity: 1)
+        // Explicitly clear this memory before use
+        error.pointee = nil
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift:248]: This seems wild! Do we not overwrite the pointee when setting the error pointer on the Rust side?

I looked for more Swift resources explaining this in more detail, but couldn't find any. If you have them, please link.

**Review by gordonbrander — APPROVED** [review]
Approve with question

File: xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift (hunk 1 above)
Comment (jsantell) [reply xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift:248]: In lieu of other (less idiomatic) solutions, explicitly initializing the error pointer as `nil` is necessary to determine whether or not a noosphere method set an error, otherwise checking `error.pointee` would dereference as neither an error object nor nil and throw a BAD_ACCESS

**Comment by bfollington** [comment]
Possible that this will fix https://github.com/subconsciousnetwork/subconscious/issues/749
