### PR TITLE
Index peers serially (and other performance enhancements)

### LINKED ISSUE #943: App seems to be requesting too often, resulting in long timeouts
On main, the app is taking longer (30s-60s) to resolve and fallback to cached 3p sphere content than it should (5s). It seems that we are hitting the gateway too often somewhere and causing redundant requests, stacking timeouts.

@cdata says:

>  It definitely looks like the app is hammering the gateway over and over again trying to get a thing it will never get. My guess is that there is a hot path here where you traverse to a sphere to read one thing and then discard that sphere, repeat for every slug (or something like that where there is N>1 things to do for that sphere). If this is the case, you'll have N*T seconds of wait time most likely, where T is the max timeout (~5s). So, 35s could be 7 things timing out one after another. It's not outright bad to discard a sphere N times, but it would certainly be better not to do that if possible.

> I was able to reproduce Gordon's case in prod for my "following" view. From the gateway logs, I saw a request to traverse to the same sphere multiple times one after another. (And, in this case, it was a sphere that referenced a missing block, so it timed out over and over)

### PR DESCRIPTION
**Pull request by bfollington**
# Changes

1. Index peers in serial, never concurrently (introduce `Task.yield()` between each peer)
2. Pass `sphere` reference around in `UserProfileService` to minimise excessive init/deinit
3. Prevent excessive profile refreshing
4. Prevent refreshing profile if it's already loading
5. Log each step of producing the profile view
6. Fix bug: we were loading the data for the entire profile view just to get our nickname on startup

None of these dramatically changed anything for me in testing but they do all incrementally improve performance.

Fixes #943

### CODE REVIEW

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 1]
```diff
@@ -2006,63 +2003,67 @@ struct AppModel: ModelProtocol {
...
+                do {
+                    let peer = try await environment.data.indexPeer(
+                        petname: petname
+                    )
+                    success.append(peer)
+                    await Task.yield()
+                } catch {
+                    fail.append(petname)
+                }
             }
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/AppView.swift:2033]: Running indexing serially instead of concurrently. We should factor this into a method.

File: xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift [hunk 2]
```diff
@@ -80,9 +80,9 @@ struct FollowTabView: View {
         ForEach(store.state.following) { follow in
             StoryUserView(
                 story: follow,
-                action: { _ in
+                action: { address in
                     notify(
-                        .requestNavigateToProfile(follow.user.address)
+                        .requestNavigateToProfile(address)
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift:85]: Extra bug I caught while investigating. This could result in using a non-optimal address to reach a peer before.

File: xcode/Subconscious/Shared/Services/UserProfileService.swift [hunk 3]
```diff
@@ -167,26 +167,26 @@ actor UserProfileService {
     /// Because profile data is optional and we expect it will not always be present
     /// any errors are logged & handled and nil will be returned if reading fails.
     func readProfileMemo(
-        address: Slashlink
+        sphere: SphereProtocol
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Services/UserProfileService.swift:170]: Avoid traversal in `noosphere.read` by passing the sphere instance.

File: xcode/Subconscious/Shared/Services/UserProfileService.swift [hunk 4]
```diff
@@ -206,23 +206,24 @@ actor UserProfileService {
     
     /// Load the underlying `_profile_` memo for a user and construct a `UserProfile` from it.
     private func loadProfileFromMemo(
-        did: Did,
+        sphere: SphereProtocol,
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Services/UserProfileService.swift:209]: Thread `sphere` through

File: xcode/Subconscious/Shared/Services/UserProfileService.swift [hunk 5]
```diff
@@ -251,10 +252,10 @@ actor UserProfileService {
     
     /// Takes a list of slugs and prepares an `EntryStub` for each, excluding hidden slugs.
     private func loadEntries(
+        sphere: SphereProtocol,
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Services/UserProfileService.swift:255]: Avoid opening the sphere again, pass reference through

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 6]
```diff
@@ -1257,12 +1252,12 @@ struct AppModel: ModelProtocol {
...
     
     static func fetchNicknameFromProfileMemo(
-        state: AppModel,
+        state: AppModel, 
         environment: AppEnvironment
     ) -> Update<AppModel> {
         let fx: Fx<AppAction> = Future.detached {
-            let response = try await environment.userProfile.requestOurProfile()
-            if let nickname = response.profile.nickname {
+            let response = try await environment.userProfile.readOurProfile(alias: nil)
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/AppView.swift:1259]: We were asking for **way** more data than we needed before just to get our nickname.

File: xcode/Subconscious/Shared/Services/UserProfileService.swift [hunk 7]
```diff
@@ -167,26 +167,26 @@ actor UserProfileService {
...
+        sphere: SphereProtocol
     ) async -> UserProfileEntry? {
+        let identity = try? await sphere.identity()
         do {
-            guard address.isProfile else {
-                throw UserProfileServiceError.attemptToReadProfileFromInvalidAddress
-            }
-            
-            let data = try? await noosphere.read(slashlink: address)
+            let data = try? await sphere.read(slashlink: Slashlink.ourProfile)
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Services/UserProfileService.swift:174]: Since we have a sphere reference "ourProfile" is always "this sphere's profile"

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 8]
```diff
@@ -951,7 +944,7 @@ struct UserProfileDetailModel: ModelProtocol {
     ) -> Update<Self> {
         update(
             state: state,
-            action: .refresh(forceSync: true),
+            action: .refresh(forceSync: false),
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:947]: We shouldn't need to sync after resolution, because resolution comes as result of a sync.

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 9]
```diff
@@ -964,7 +957,7 @@ struct UserProfileDetailModel: ModelProtocol {
         logger.log("Failed to resolve followed user: \(error)")
         return update(
             state: state,
-            action: .refresh(forceSync: true),
+            action: .refresh(forceSync: false),
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:960]: We shouldn't sync after a failed resolution either.

**Review by gordonbrander — APPROVED** [review]
Straightforward improvements.

I left a couple of suggestions. The only important one is to factor out the indexing code into a method of DataService.

Playtested in dev.

File: xcode/Subconscious/Shared/Services/UserProfileService.swift (hunk 7 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Services/UserProfileService.swift:174]: "ourProfile" just means a peerless slashlink of `/_profile_` which should always point to _that sphere's_ profile. I can change the code to read more clearly though and use `Slashlink(slug: Slug.profile)`?

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 10]
```diff
@@ -1257,12 +1249,12 @@ struct AppModel: ModelProtocol {
     }
     
     static func fetchNicknameFromProfileMemo(
-        state: AppModel,
+        state: AppModel, 
         environment: AppEnvironment
     ) -> Update<AppModel> {
         let fx: Fx<AppAction> = Future.detached {
-            let response = try await environment.userProfile.requestOurProfile()
```
[the remark this answers is not in the document]
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/AppView.swift:1264]: Yah, I thought something similar while working, good call.

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 11]
```diff
@@ -211,9 +210,8 @@ enum AppAction {
     case failCollectPeersToIndex(_ error: String)
 
     /// Index the contents of a sphere in the database
-    case indexPeer(_ petname: Petname)
-    case succeedIndexPeer(_ peer: PeerRecord)
-    case failIndexPeer(petname: Petname, error: Error)
+    case indexPeers(_ petnames: [Petname])
+    case completeIndexPeers(succeeded: [PeerRecord], failed: [Petname])
```
[the remark this answers is not in the document]
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/AppView.swift]: Done!

File: xcode/Subconscious/Shared/Components/AppView.swift (hunk 1 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/AppView.swift]: I managed to add some tests to assert concurrency behaviour around yielding, but I can't think of a way to _actually_ index a peer without a gateway in the mix.

It might be possible if we have mocked versions of every service `DataService` calls out to but... I'm not a huge fan of writing 100s of lines of mocks which can just as easily introduce problems.
