### PR TITLE
Replace FAB Orb Shader with Gradient

### LINKED ISSUE #376: "Orb" subsurface shader crashes under iOS16
```log
2022-11-08 08:59:44.420798-0500 Subconscious[526:9956] Metal GPU Frame Capture Enabled
2022-11-08 08:59:44.421290-0500 Subconscious[526:9956] Metal API Validation Enabled
2022-11-08 08:59:44.482445-0500 Subconscious[526:9956] Errors found! Invalidating cache...
2022-11-08 08:59:44.499726-0500 Subconscious[526:9956] Errors found! Invalidating cache...
2022-11-08 08:59:44.560001-0500 Subconscious[526:9956] [Metal Compiler Warning] Warning: Compilation succeeded with: 

program_source:179:19: warning: unused variable 'midpoint_xy'
    metal::float2 midpoint_xy = 0.5 * resolution;
                  ^
program_source:202:11: warning: unused variable 'ttt'
    float ttt = metal::clamp(_e75 + 0.10000000149011612, 0.0, 1.0);
          ^
program_source:213:11: warning: unused variable 'occlusion_alpha'
    float occlusion_alpha = (_e160 * _e160) * 0.8500000238418579;
          ^
2022-11-08 08:59:44.562379-0500 Subconscious[526:9956] [Metal Compiler Warning] Warning: Compilation succeeded with: 

program_source:179:19: warning: unused variable 'midpoint_xy'
    metal::float2 midpoint_xy = 0.5 * resolution;
                  ^
program_source:202:11: warning: unused variable 'ttt'
    float ttt = metal::clamp(_e75 + 0.10000000149011612, 0.0, 1.0);
          ^
program_source:213:11: warning: unused variable 'occlusion_alpha'
    float occlusion_alpha = (_e160 * _e160) * 0.8500000238418579;
          ^
thread '<unnamed>' panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:425:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libc++abi: terminating with uncaught foreign exception
terminating with uncaught foreign exception
```

### PR DESCRIPTION
**Pull request by bfollington**
Fixes #376 (by removing the shader). Confirmed that this works on iOS 16.3.1 on-device.

This PR replaces the old FAB button style with one based on the Subconscious brand mark. All colours and styles were referenced directly from our brand [styleguide](https://drive.google.com/drive/u/4/folders/1kZJ5svfLPBWSXVY9YWbexdclIYJi-QS9) including colour names etc.

## Dark Preview
image

## Light Preview
image

### CODE REVIEW

File: xcode/Subconscious/Shared/AppTheme.swift [hunk 1]
```diff
@@ -92,4 +92,52 @@ extension Color {
...
     static let fabTextDisabled = fabText.opacity(0.3)
     static let scrim = SwiftUI.Color(UIColor.tertiarySystemFill)
+    
+    // MARK: Brand colours
+    // Brand Mark
+    static let brandMarkPink = Color(uiColor: UIColor(red: 255/255, green: 163/255, blue: 186/255, alpha: 1)) // #FFA3BA
+    static let brandMarkViolet = Color(uiColor: UIColor(red: 197/255, green: 112/255, blue: 219/255, alpha: 1)) // #C570DB
+    static let brandMarkCyan = Color(uiColor: UIColor(red: 48/255, green: 255/255, blue: 233/255, alpha: 1)) // #30FFE9
+    static let brandMarkRed = Color(uiColor: UIColor(red: 255/255, green: 94/255, blue: 135/255, alpha: 1)) // #FF5E87
+    static let brandMarkPurple = Color(uiColor: UIColor(red: 132/255, green: 42/255, blue: 156/255, alpha: 1)) // #842A9C
```
Comment (bfollington) [inline xcode/Subconscious/Shared/AppTheme.swift:102]: style: Should we simplify these to normalized values or leave in the 255 format?

File: xcode/Subconscious/Shared/AppTheme.swift [hunk 2]
```diff
@@ -92,4 +92,52 @@ extension Color {
...
+    static let brandBgPurple = Color(uiColor: UIColor(red: 71/255, green: 30/255, blue: 68/255, alpha: 1)) // #471E44
+    static let brandBgBlack = Color(uiColor: UIColor(red: 35/255, green: 31/255, blue: 32/255, alpha: 1)) // #231F20
+    static let brandBgSlate = Color(uiColor: UIColor(red: 57/255, green: 50/255, blue: 84/255, alpha: 1)) // #393254
+    
+    // Eyeballed to match brandmark
+    static let brandLightMarkGradient = [
+        Gradient.Stop(color: Color.brandMarkPink, location: 0),
+        Gradient.Stop(color: Color.brandMarkViolet, location: 0.50),
+        Gradient.Stop(color: Color.brandMarkViolet, location: 0.60),
+        Gradient.Stop(color: Color.brandMarkCyan, location: 0.95)
```
Comment (bfollington) [inline xcode/Subconscious/Shared/AppTheme.swift:117]: This might seem excessive but it looked crap without manually tuning the stop spacing.

File: xcode/Subconscious/Shared/AppTheme.swift [hunk 3]
```diff
@@ -92,4 +92,52 @@ extension Color {
...
+        colorScheme == .dark ? Color.brandMarkPurple : Color.brandMarkPink
+    }
+    
+    static func brandText(_ colorScheme: ColorScheme) -> Color {
+        colorScheme == .dark ? Color.white : Color.brandBgSlate
+    }
+    
+    static func brandDropShadow(_ colorScheme: ColorScheme) -> Color {
+        colorScheme == .dark ? Color.brandMarkPink : Color.brandMarkPurple
+    }
```
Comment (bfollington) [inline xcode/Subconscious/Shared/AppTheme.swift:142]: Is there a better/preferred pattern for colours that are conditional on light vs dark?

File: xcode/Subconscious/Shared/Config.swift [hunk 4]
```diff
@@ -21,7 +21,7 @@ struct Config: Equatable, Codable {
     var pollingInterval: Double = 15
 
     /// Subsurface "orb" shader on main FAB
-    var orbShaderEnabled = true
+    var orbShaderEnabled = false
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Config.swift:24]: Tempted to strip this config value and the if statement from the code, but it's not required to resolve the issue.

File: xcode/Subconscious/Shared/AppTheme.swift (hunk 1 above)
Comment (gordonbrander) [reply xcode/Subconscious/Shared/AppTheme.swift:102]: This works for me.

Non-blocking: we might could simplify with `SwiftUI.Color` constructors:

- https://developer.apple.com/documentation/swiftui/color/init(hue:saturation:brightness:opacity:)
- https://developer.apple.com/documentation/swiftui/color/init(_:red:green:blue:opacity:)

No need to change for this PR.

File: xcode/Subconscious/Shared/AppTheme.swift (hunk 3 above)
Comment (gordonbrander) [reply xcode/Subconscious/Shared/AppTheme.swift:142]: This seems right to me.

File: xcode/Subconscious/Shared/Config.swift (hunk 4 above)
Comment (gordonbrander) [reply xcode/Subconscious/Shared/Config.swift:24]: Optional: we can strip.

**Review by gordonbrander — APPROVED** [review]
