### PR TITLE
Fix (possible) delay on tapping links

### LINKED ISSUE #957: Tapping on a link can have long delay before navigating
When we tap a link we seem to be `traversing` to calculate the address before pushing a new detail onto the stack. This results in a long wait where you can tap repeatedly and queue up multiple navigations.

Steps:

1. View a 3P note with a peered link (i.e. `@peer/slashlink`) in it
2. Tap the link multiple times (may only be possible with sufficient network latency)
3. Observe as nothing happens, then after a while, multiple copies of the detail are pushed onto the stack

### PR DESCRIPTION
**Pull request by bfollington**
Fixes #957 

- Ensure DID is known at link traversal time
    - Thread the DID through from whatever context the link is being tapped in, lets us skip `noosphere.resolve`
- Don't let `context` make its way to the `DetailStackModel`

### CODE REVIEW

File: xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift [hunk 1]
```diff
@@ -76,8 +76,8 @@ struct StoryEntryView: View {
                         onViewTransclude: { slashlink in
                             onRequestDetail(slashlink, story.entry.excerpt.description)
                         },
-                        onTranscludeLink: { address, link in
-                            onLink(address, link)
+                        onTranscludeLink: { entry, link in
+                            onLink(entry, link)
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift:80]: Call it `context.

File: xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift [hunk 2]
```diff
@@ -306,14 +308,14 @@ struct DetailStackModel: Hashable, ModelProtocol {
     static func findAndPushLinkDetail(
         state: Self,
         environment: Environment,
+        did: Did,
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift:311]: Call this `owner`

File: xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift [hunk 3]
```diff
@@ -86,7 +92,8 @@ struct MemoEditorDetailView: View {
                             .padding(.bottom, AppTheme.unit4)
                         BacklinksView(
                             backlinks: store.state.backlinks,
-                            onRequestDetail: { link in
+                            onRequestDetail: {
+                                link in
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift:96]: Prev line

File: xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift [hunk 4]
```diff
@@ -96,8 +103,16 @@ struct MemoEditorDetailView: View {
                                     )
                                 )
                             },
-                            onLink: { address, link in
-                                notify(.requestFindLinkDetail(address, link: link))
+                            onLink: {
+                                context,
+                                link in
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift:108]: prev line

File: xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift [hunk 5]
```diff
@@ -102,7 +102,12 @@ struct MemoViewerDetailView: View {
 
 /// View for the "not found" state of content
 struct MemoViewerDetailNotFoundView: View {
-    var backlinks: [EntryStub]
+    @ObservedObject var store: Store<MemoViewerDetailModel>
+    
+    var backlinks: [EntryStub] {
+        store.state.backlinks
+    }
+
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift:110]: Revert?

File: xcode/Subconscious/Shared/Components/Feed/FeedListView.swift [hunk 6]
```diff
@@ -33,11 +33,12 @@ struct FeedListView: View {
                                 )
                             )
                         },
-                        onLink: { address, link in
+                        onLink: { entry, link in
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Feed/FeedListView.swift:36]: call it `context`

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 7]
```diff
@@ -540,6 +540,9 @@ struct AppModel: ModelProtocol {
     /// This property is updated at `.start` with the corresponding value
     /// stored in `AppDefaults`.
     var sphereIdentity: String?
+    var sphereDid: Did? {
+        Did(sphereIdentity ?? "")
+    }
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/AppView.swift:545]: We were doing this all over the place, may as well centralize it.

Comment (gordonbrander) [reply xcode/Subconscious/Shared/Components/AppView.swift:545]: Optional: we could consider doing this when assigning the value to the model.

File: xcode/Subconscious/Shared/Components/BacklinksView.swift [hunk 8]
```diff
@@ -10,7 +10,7 @@ import SwiftUI
 struct BacklinksView: View {
     var backlinks: [EntryStub]
     var onRequestDetail: (EntryLink) -> Void
-    var onLink: (_ context: Slashlink, SubSlashlinkLink) -> Void
+    var onLink: (_ context: EntryStub, SubSlashlinkLink) -> Void
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/BacklinksView.swift:13]: I'm generally in favor of passing as little information as possible to callbacks. A few open-ended thoughts...

IIRC there are a few places now where we need to pass a did with the slashlink. This feels like a hint that `slashlink` is not giving us everything we need to do addressing in every case.

We have the `Link` type which is an identifier made up of did + slug. If this is an option here, I would rather use it. However, this does lose petname information, which may be useful.

It pains me to say it but we may want to introduce an `Address` type that contains a DID plus slashlink, or perhaps a `Did`, `Petname?` and `Slug`.

Thoughts?

File: xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift [hunk 9]
```diff
@@ -169,8 +175,13 @@ struct MemoViewerDetailLoadedView: View {
             return .systemAction
         }
         
+        guard let did = user?.did else {
+            return .systemAction
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift:179]: I don't think we want to default to system action here, since we know this will be a `sub://` URL.

Instead, we want to return `.handled` and log what went wrong.

However, I also think that we should be encoding everything we need to follow a URL into the URL. Let's consider adding the necessary DID to the URL.

BTW what role does the DID play in looking up the URL?

**Review by gordonbrander — CHANGES_REQUESTED** [review]
A few questions and asks. Thanks!

File: xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift (hunk 9 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift:179]: > what role does the DID play in looking up the URL?

The DID is how we detect if we know this user by another (shorter) name. We may tap a link to `@ben.gordon.chris/hello` but if we follow `@ben` already we want to land on `@ben/hello`. If we don't pass the DID through then we have to call `resolve` on `@ben.gordon.chris`, introducing latency.

File: xcode/Subconscious/Shared/Components/BacklinksView.swift (hunk 8 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/BacklinksView.swift:13]: Yep, I agree that the triple of `DID` + `Slashlink` or `DID` + `Petname?` + `Slug` deserves a type. I like the sound of `Address`, I'll explore that path.

File: xcode/Subconscious/Shared/Components/AppView.swift (hunk 7 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/AppView.swift]: Done!

File: xcode/Subconscious/Shared/Components/BacklinksView.swift (hunk 8 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/BacklinksView.swift]: I ended up going with a more specific name: `ResolvedAddress`. We use the term address all over the codebase to refer to a `Slashlink` and from my POV a Slashlink is the most common kind of address in the app. `ResolvedAddress` is an attempt to carve out a more specific role.

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 10]
```diff
@@ -546,6 +546,8 @@ struct AppModel: ModelProtocol {
     /// This property is updated at `.start` with the corresponding value
     /// stored in `AppDefaults`.
     var sphereIdentity: String?
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppView.swift:548]: Can we drop `sphereIdentity` given we have `sphereDid`?

File: xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift [hunk 11]
```diff
@@ -169,17 +174,22 @@ struct MemoViewerDetailLoadedView: View {
             return .systemAction
         }
         
+        guard let did = user?.did else {
+            MemoViewerDetailModel.logger.log("User profile is not loaded, can't handle link")
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift:178]: Nit: I wouldn't mind giving the view its own logger.

**Review by gordonbrander — APPROVED** [review]
LGTM
