### PR TITLE
Make all calls to Noosphere non-blocking on main thread

### LINKED ISSUE #439: App becomes non-responsive during sync with invalid gateway
This _may_ be a simulator only issue (I'm currently unable to test this on-device due to #376). 

# Reproduction

1. App setup (create a sphere)
2. Configure your gateway URL with Tailscale running 
3. Sync with gateway successfully (unsure if we need this step)
4. Quit app
5. Kill Tailscale (so gateway is unreachable)
6. Re-open app
7. Tap settings icon
8. Watch the app hang until the the request to the gateway times out (60 seconds for me)
9. Settings sheet finally opens, showing error

If you manually run sync again, close the sheet and try to re-open it the app will hang until the timeout error occurs again.

Screenshot 2023-03-09 at 12 13 04 pm

# Expected Behaviour

Sync would run and fail in the background, letting me use the app in the meantime.

# Notes

My gateway URL is `http://bfollington.sphere.test.subconscious.cloud` and I suspect that 50% of the issue stems from the fact that pinging that URL (without Tailscale) takes 60 seconds to actually timeout. Using a localhost gateway like `http://127.0.0.1:4433` instantly times out instead of waiting.

Of course, the UI should still not be blocking during that waiting period.

Here's a video of the issue:

https://user-images.githubusercontent.com/5009316/223899842-e6b237cb-b563-40d8-ba85-6a8012ad480a.mov

### PR DESCRIPTION
**Pull request by gordonbrander**
Fixes #439 

There are a few places where we have inadvertently called Noosphere synchronously on the main thread, causing the UI to block on certain long operations, like syncing. This should never happen.

This PR fixes the issue, and makes services Swift `actor`s to make it difficult to trip over this footgun. Actors are isolated, and can only be accessed via async/await. This means you cannot accidentally call blocking synchronous APIs on an actor (as I found we were doing in a number of subtle places). You must await, or else wrap in some kind of callback or publisher. This prevents us from accidentally causing UI hangs.

## Notes

- `NoosphereService`, `Noosphere` and `Sphere` are now Swift `actor`s. That means they always run off of the main thread, and are isolated (can only be accessed from the outside via `async`/`await` or via thread-safe things like publishers).
    - Swift manages a cooperative threadpool of non-main-thread threads for all actors. The thread pool is concurrent.
- A new `SpherePublisherProtocol` exposes nonisolated publishers for Noosphere actions.
    - `NoosphereService` conforms to `SpherePublisherProtocol`
- Services have been "flattened". App Environment holds a bag of services, each of which do one job.
    - Services may depend upon each other by passing in references during construction
    - Services keep their dependencies private. This means there is no calling `data.noosphere` anymore. If you need `noosphere`, you should just call `noosphere`.
    - Services are expected to handle their own thread-safety/atomicity if needed
- This gets us most of the way to the design discussed in #462 
    - I tried exposing only protocols for services, so that components could specify only the requirements they needed. However, this had a lot of sharp edges. Swift's type system is just not up to the task of generics with protocol constraints. I ended up going back to environments made up of concrete types.

### CODE REVIEW

File: xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift [hunk 1]
```diff
@@ -64,8 +63,66 @@ public protocol SphereProtocol {
     func traverse(petname: Petname) throws -> Sphere
 }
 
-protocol SphereIdentityProtocol {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift:67]: No longer used anywhere, so I removed it. Would prefer to make this part of SphereProtocol anyway.

File: xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift [hunk 2]
```diff
@@ -64,8 +63,66 @@ public protocol SphereProtocol {
...
-    func identity() throws -> String
+/// Describes a Sphere using a Combine Publisher-based API.
+/// See `Sphere` for concrete implementation.
+public protocol SpherePublisherProtocol {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift:68]: An asynchronous publisher-based protocol that mirrors the synchronous one.

File: xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift [hunk 3]
```diff
@@ -97,6 +154,10 @@ public final class Sphere: SphereProtocol {
     public let sphere: OpaquePointer
     public let identity: String
     
+    private var queue: DispatchQueue {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift:157]: Use same queue as the Noosphere instance

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 4]
```diff
@@ -1171,6 +1205,11 @@ struct AppEnvironment {
     var documentURL: URL
     var applicationSupportURL: URL
 
+    private var _noosphere: NoosphereService
+    var noosphere: some NoosphereServiceProtocol { _noosphere }
+    /// Exposes sphere publisher protocol for Noosphere
+    var sphere: some SpherePublisherProtocol { _noosphere }
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppView.swift:1211]: We use `some` to expose only certain protocols from the caller side.

`some` does caller-side type-erasure, so that the type remains concrete in `AppEnvironement`, but the caller may only interact with the protocol, and not the underlying type.

The protocols we expose are "UI-thread-friendly". That is, if they are blocking, they are very fast, and if they aren't very fast, they produce Combine publishers and run on a separate thread.

File: xcode/Subconscious/Shared/Library/CombineUtilities.swift [hunk 5]
```diff
@@ -41,3 +41,74 @@ struct CombineUtilities {
         .eraseToAnyPublisher()
     }
 }
+
+extension DispatchQueue {
+    /// Run a closure async on this queue, returning a Combine Future.
+    func future<T>(
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Library/CombineUtilities.swift:47]: Create a Combine future from an async work item on a GDC queue. This helper is similar in principle to the `CombineUtilities.async` helper, but gives us more control over which GDC queue things are run on.

In future, I would like to move all of our uses of `CombineUtilities.async` to `DispatchQueue.future`.

File: xcode/Subconscious/Shared/Services/DataService.swift [hunk 6]
```diff
@@ -85,9 +85,7 @@ struct DataService {
 
     /// Sync local state to gateway
     func syncSphereWithGateway() -> AnyPublisher<String, Error> {
-        CombineUtilities.async(qos: .utility) {
-            try noosphere.sync()
-        }
+        noosphere.syncPublisher()
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/DataService.swift:88]: Noosphere handles its own async publisher stuff now.

File: xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift [hunk 7]
```diff
@@ -27,25 +28,37 @@ enum NoosphereServiceError: Error, LocalizedError {
     }
 }
 
+protocol NoosphereServiceProtocol {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift:31]: Exposes basic controls for interacting with memoized Noosphere/Sphere instance.

File: xcode/Subconscious/Shared/Components/AddressBook/AddressBookModel.swift [hunk 8]
```diff
@@ -36,40 +41,50 @@ struct FollowUserFormModel: Equatable {
 }
 
 struct PetnameFieldCursor: CursorProtocol {
-    static func get(state: AddressBookModel) -> FormField<String, Petname> {
+    typealias Model = AddressBookModel
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AddressBook/AddressBookModel.swift:44]: These changes were byproducts of experimenting with type-erased generics. I ended up going back to concrete types for services, but the typealiases may as well stay. It's cleaner.

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 9]
```diff
@@ -391,7 +396,7 @@ struct AppModel: ModelProtocol {
             return AppAddressBookCursor.update(
                 state: state,
                 action: action,
-                environment: environment.addressBook
+                environment: AddressBookEnvironment(environment)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppView.swift:399]: Constructing AddressBookEnvironment on the fly instead.

The way I've got this set up at the moment is environments hold services. Services are classes (or maybe actors in future), but environments are just structs to hold these services. This makes them cheap to create and throw away, provided the services are just passed down by reference. I've created a convenience initializer for `AddressBookEnvironment` that takes an `AppEnvironment`.

File: xcode/Subconscious/Shared/Services/DataService.swift [hunk 10]
```diff
@@ -38,10 +38,10 @@ struct MoveReceipt: Hashable {
...
 /// access methods for the app.
 struct DataService {
-    var addressBook: AddressBookService
-    var noosphere: NoosphereService
-    var database: DatabaseService
-    var local: HeaderSubtextMemoStore
+    private var addressBook: AddressBookService
+    private var noosphere: NoosphereService
+    private var database: DatabaseService
+    private var local: HeaderSubtextMemoStore
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/DataService.swift:44]: Dependencies of NoosphereService should be private.

File: xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift [hunk 11]
```diff
@@ -14,6 +15,8 @@ import os
 public protocol SphereProtocol {
     associatedtype Memo
     
+    func identity() throws -> String
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift:18]: The protocol allows for throwing identity so that we can implement this signature in `NoosphereService`, where it might fail.

**Comment by gordonbrander** [comment]
Unfortunately I discovered another UI blocker (back button save) and am tracking down source. This PR is not ready yet.

File: xcode/Subconscious/Shared/Services/AddressBookService.swift [hunk 12]
```diff
@@ -43,115 +43,115 @@ class AddressBookService {
     /// Get the full list of entries in the address book.
     /// This is cached after the first use unless requested using refetch.
     /// If an error occurs producing the entries the resulting list will be empty.
-    func listEntries(refetch: Bool = false) -> AnyPublisher<[AddressBookEntry], Never> {
-        if let entries = addressBook {
+    func listEntries(
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/AddressBookService.swift:46]: Refactor this logic using async/await semantics. It reads more clearly.

**Comment by gordonbrander** [comment]
Swift async uses a small thread pool and expects IO to be async so that fn can yield to other work while io is happening.

Until we get Noosphere's non-blocked reads and callback-based non blocking api, we might want to shove Noosphere onto the global queue even though it's an actor already.

https://developer.apple.com/forums/thread/708664

File: xcode/Subconscious/Shared/Library/CombineUtilities.swift [hunk 13]
```diff
@@ -8,36 +8,87 @@
...
+            }
+        }
+    }
+}
+
+extension Publisher {
+    /// Recover from a failure.
+    /// Similar to `catch` but allows you to map an `Error` to an `Output`,
+    /// without having to wrap in a publisher.
+    func recover(
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Library/CombineUtilities.swift:87]: 💯

File: xcode/Subconscious/Shared/Components/AddressBook/AddressBookView.swift [hunk 14]
```diff
@@ -58,7 +58,6 @@ struct AddressBookView: View {
             .toolbar {
                 ToolbarItem(placement: .cancellationAction) {
                     Button("Close", role: .cancel) {
-                        AddressBookModel.logger.debug("Close Address Book")
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AddressBook/AddressBookView.swift:61]: Not needed / if needed should be in update function.

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 15]
```diff
@@ -988,16 +1080,10 @@ struct AppModel: ModelProtocol {
...
-            logger.log("No gateway configured. Skipping sync.")
-            return Update(state: state)
-        }
-        
         var model = state
         model.lastGatewaySyncStatus = .pending
-        
-        logger.log("Syncing with gateway: \(gatewayURL.absoluteString)")
-        let fx: Fx<AppAction> = environment.data.syncSphereWithGateway()
+        logger.log("Syncing with gateway: \(model.gatewayURL)")
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppView.swift:1085]: We no longer have synchronous access to this property on the actor, so we use the copy on the model instead (the update fn keeps it up-to-date)

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 16]
```diff
@@ -1221,30 +1310,43 @@ struct AppEnvironment {
             gatewayURL: defaultGateway,
             sphereIdentity: defaultSphereIdentity
         )
+        self.noosphere = noosphere
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppView.swift:1313]: Keep Noosphere around. Now that services are "flattened" we need to make sure we have one property for each service.

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 17]
```diff
@@ -1221,30 +1310,43 @@ struct AppEnvironment {
...
 
-        let databaseService = DatabaseService(
+        let database = DatabaseService(
             database: SQLite3Database(
                 path: databaseURL.absoluteString,
                 mode: .readwrite
             ),
             migrations: Config.migrations
         )
+        self.database = database
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppView.swift:1325]: Keep database around on service.

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 18]
```diff
@@ -1221,30 +1310,43 @@ struct AppEnvironment {
...
         
-        let addresBook = AddressBookService(noosphere: noosphere, database: databaseService)
+        let addressBook = AddressBookService(
+            noosphere: noosphere,
+            database: database
+        )
+        self.addressBook = addressBook
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppView.swift:1331]: Keep address book around on service.

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 19]
```diff
@@ -1221,30 +1310,43 @@ struct AppEnvironment {
...
+            addressBook: addressBook
         )
         
-        self.addressBook = AddressBookEnvironment(data: data)
-
         self.feed = FeedService()
     }
 }
 
+extension AddressBookEnvironment {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppView.swift:1344]: Extension to easily construct AddressBookEnvironment from AppEnvironment. Note relationship of extension = AppEnvironment knows about AddressBookEnvironment, but AddressBookEnvironment doesn't know about AppEnvironment. This mirrors component relationship where parents may know about children, but children may not know about parents.

File: xcode/Subconscious/Shared/Components/Notebook/Notebook.swift [hunk 20]
```diff
@@ -939,18 +939,18 @@ struct NotebookModel: ModelProtocol {
...
-        let address = environment.data
-            .findAddressInOurs(slug: slug) ?? fallbackAddress
-        return update(
-            state: state,
-            action: .pushDetail(
-                MemoEditorDetailDescription(
-                    address: address,
-                    fallback: fallback
+        let fx: Fx<NotebookAction> = environment.data
+            .findAddressInOursPublisher(slug: slug)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Notebook/Notebook.swift:943]: Fix sync call.

File: xcode/Subconscious/Shared/Library/CombineUtilities.swift [hunk 21]
```diff
@@ -8,36 +8,87 @@
...
-        Future({ promise in
-            DispatchQueue.global(qos: qos).async(execute: {
-                let result: T = execute()
-                promise(.success(result))
-            })
-        })
-        .eraseToAnyPublisher()
+/// Create a Combine Future from an async closure that never fails.
+/// Async actions are run in a task and fulfil the future's promise.
+public extension Future where Failure == Never {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Library/CombineUtilities.swift:13]: New convenience extensions to `Future` allow us to easily create Combine Futures from async functions.

This gives us much more flexibility in constructing publishers from async functions where and when we need them. It also takes advantage of Swift's new concurrency primitives (Tasks, Actors, async/await) for more ergonomic and efficient concurrency.

This replaces the older `CombineUtilities.async` helper, which scheduled things on the global queue.

File: xcode/Subconscious/Shared/Components/AddressBook/AddressBookModel.swift [hunk 22]
```diff
@@ -18,10 +18,17 @@ struct AddressBookEntry: Equatable {
 }
 
 struct AddressBookEnvironment {
+    // Default logger for environment
+    static let logger = Logger(
+        subsystem: Config.default.rdns,
+        category: "AddressBook"
+    )
+    var logger: Logger = logger
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/AddressBook/AddressBookModel.swift:26]: Nice!

**Review by bfollington — APPROVED** [review]
LGTM!
