### PR TITLE
Fix delete note from detail view

### LINKED ISSUE #941: Deleting from note detail does not work
Steps to reproduce

- Create a note
- Save it
- Tap omnibox
- Tap delete

What happens: note is not deleted.

What should happen: note is deleted.

We're probably failing to send up the right notification.

### PR DESCRIPTION
**Pull request by gordonbrander**
Fixes #941

- [x] Fix Notebook tab
    - [x] Fix deletion
    - [x] Add tests
- [x] Fix Feed tab
    - [x] Fix deletion
    - [x] Add tests
- [x] Fix Profile tab
    - [x] Fix deletion
    - [x] Add tests

QA:

- [x] Notebook tab
    - [x] Check delete
    - [x] Check rename
    - [x] Check change audience
- [x] Feed tab
    - [x] Check delete
    - [x] Check rename
    - [x] Check change audience
- [x] Profile tab
    - [x] Check delete
    - [x] Check rename
    - [x] Check change audience

### CODE REVIEW

File: xcode/Subconscious/Shared/Components/Notebook/Notebook.swift [hunk 1]
```diff
@@ -115,7 +115,7 @@ enum NotebookAction {
     /// Set the count of existing entries
     case setEntryCount(Int)
     /// Fail to get count of existing entries
-    case failEntryCount(Error)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Notebook/Notebook.swift:118]: Necessary to make NotebookAction Hashable, and we need it to be Hashable so that we can test for value equality in the tests.

File: xcode/Subconscious/Shared/Services/DatabaseService.swift [hunk 2]
```diff
@@ -12,7 +12,7 @@ import Combine
 import os
 
 /// Enum representing the current readiness state of the database service
-enum DatabaseServiceState: String {
+enum DatabaseServiceState: String, Hashable {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Services/DatabaseService.swift:15]: Necessary to make NotebookAction Hashable.

File: xcode/Subconscious/Shared/Components/Notebook/Notebook.swift [hunk 3]
```diff
@@ -575,15 +577,16 @@ struct NotebookModel: ModelProtocol {
...
-        let fx: Fx<NotebookAction> = environment.data.countMemosPublisher()
+        let fx: Fx<NotebookAction> = environment.data
+            .countMemosPublisher()
             .map({ count in
                 NotebookAction.setEntryCount(count)
             })
-            .catch({ error in
-                Just(NotebookAction.failEntryCount(error))
+            .recover({ error in
+                NotebookAction.failEntryCount(error.localizedDescription)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Notebook/Notebook.swift:586]: Box localizedDescription, not actual error.

File: xcode/Subconscious/Shared/Components/Notebook/Notebook.swift [hunk 4]
```diff
@@ -211,6 +211,8 @@ struct NotebookDetailStackCursor: CursorProtocol {
 
     static func tag(_ action: ViewModel.Action) -> NotebookModel.Action {
         switch action {
+        case let .requestDeleteMemo(slashlink):
+            return .requestDeleteMemo(slashlink)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Notebook/Notebook.swift:215]: Add missing requestDelete interception. This fixes deletion in detail view.

**Comment by gordonbrander** [comment]
We do pass `AppStore` down to the MemoEditorDetailView. We could send these messages directly to it.

However, I'm not fond of treating `AppStore` as a message bus. Would prefer a strict hierarchy of views, where only the top tabs communicate to `AppStore`. Sticking to a hierarchy will make it easier to adopt `@Observable` macro as well.

MemoEditorDetailView only uses `AppStore` to refresh backlinks on `succeedIndexOurSphere`. Seems like this could be managed by the parent tab instead, and we could remove this dependency...

File: xcode/Subconscious/Shared/Components/Feed/Feed.swift [hunk 5]
```diff
@@ -112,28 +112,24 @@ struct FeedView: View {
             app.actions.compactMap(FeedAction.from),
             perform: store.send
         )
-    }
-}
-
-extension FeedAction {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Feed/Feed.swift:118]: Moved this down below `FeedAction` definition.

File: xcode/Subconscious/Shared/Components/Feed/Feed.swift [hunk 6]
```diff
@@ -112,28 +112,24 @@ struct FeedView: View {
...
-            return .requestFeedRoot
-        default:
-            return nil
+        /// Replay some feed actions on app store
+        .onReceive(
+            store.actions.compactMap(AppAction.from),
+            perform: app.send
+        )
+        .onReceive(store.actions) { action in
+            FeedAction.logger.debug("\(String(describing: action))")
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Feed/Feed.swift:121]: Feed was previously not logging its actions.

Note to self: we should get logging into `ObservableStore.Store` as a core feature, to avoid this requirement.

File: xcode/Subconscious/Shared/Components/AppTabView.swift [hunk 7]
```diff
@@ -9,7 +9,7 @@ import SwiftUI
 import ObservableStore
 import Combine
 
-enum AppTab: String {
+enum AppTab: String, Hashable {
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppTabView.swift:12]: Added Hashable conformance to several action types so that we could check them for equality in tests.

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 8]
```diff
@@ -657,7 +661,7 @@ struct UserProfileDetailModel: ModelProtocol {
         model.following = content.following
         model.loadingState = .loaded
         
-        return Update(state: model)
+        return Update(state: model).animation(.default)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:664]: Results in nice smooth animating in of updated items in user feed.

File: xcode/Subconscious/SubconsciousTests/Tests_FeedUpdate.swift
Comment (gordonbrander) [inline xcode/Subconscious/SubconsciousTests/Tests_FeedUpdate.swift:1]: Found this unused test. Removed.

File: xcode/Subconscious/Shared/Components/AppView.swift [hunk 9]
```diff
@@ -90,15 +90,15 @@ typealias InviteCodeFormField = FormField<String, InviteCode>
 typealias NicknameFormField = FormField<String, Petname.Name>
 typealias GatewayUrlFormField = FormField<String, GatewayURL>
 
-struct PeerIndexError: Error {
-    let error: Error
+struct PeerIndexError: Error, Hashable {
+    let error: String
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/AppView.swift:94]: Make field a string so that error can be hashable.

**Comment by gordonbrander** [comment]
Note to self: the current information flow goes:

- Editor sends up `requestDelete()` notification.
- Up to DetailStackAction.requestDelete()
- Up to NotebookAction.requestDelete()
- Intercepted and replayed on AppStore as `AppAction.deleteMemo()`
- Memo is deleted
- Tabs intercept and replay `.succeedDeleteMemo()`, etc.

**Comment by gordonbrander** [comment]
@bfollington this PR is ready to go, but an unrelated test `Tests_DataService.testConcurrentIndexing()` is causing the PR to fail.

I think that `Tests_DataService.testConcurrentIndexing` may be saturating the testrunner with dummy tasks. Can you say more about this test, what it is accomplishing, and how we might go about fixing this?

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 10]
```diff
@@ -633,13 +633,17 @@ struct UserProfileDetailModel: ModelProtocol {
...
+        .map { content in
+            UserProfileDetailAction.populate(content)
+        }
+        .catch { error in
+            Just(
+                UserProfileDetailAction.failedToPopulate(
+                    error.localizedDescription
+                )
+            )
+        }
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:645]: Prefer `.recover`?

File: xcode/Subconscious/Shared/Components/Feed/Feed.swift [hunk 11]
```diff
@@ -229,12 +262,12 @@ struct FeedModel: ModelProtocol {
...
     var detailStack = DetailStackModel()
     var entries: [StoryEntry]? = nil
-
+    
     static let logger = Logger(
         subsystem: Config.default.rdns,
         category: "Feed"
     )
-
+
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Feed/Feed.swift:270]: Nit: could drop this

File: xcode/Subconscious/Shared/Components/Feed/Feed.swift [hunk 12]
```diff
@@ -396,10 +451,10 @@ struct FeedModel: ModelProtocol {
                 FeedAction.succeedFetchFeed(stories)
             })
             .catch({ error in
-                Just(FeedAction.failFetchFeed(error))
+                Just(FeedAction.failFetchFeed(error.localizedDescription))
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Feed/Feed.swift:454]: Prefer `.recover`?

File: xcode/Subconscious/SubconsciousTests/Tests_Feed.swift [hunk 13]
```diff
@@ -0,0 +1,11 @@
...
+//  Tests_FeedUpdate.swift
+//  SubconsciousTests
+//
+//  Created by Gordon Brander on 8/30/22.
+//
+
+import XCTest
+
+class Tests_Feed: XCTestCase {
+}
```
Comment (bfollington) [inline xcode/Subconscious/SubconsciousTests/Tests_Feed.swift:11]: Empty file?

**Review by bfollington — APPROVED** [review]
A couple of formatting suggestions, but LGTM.

One thought: do we need `Hashable` or just `Equatable` for tests? I don't have strong feelings but I believe `Hashable` extends `Equatable` so it's a (slightly) stronger contract.
