### PR TITLE
Do not refresh viewer if content is indentical

### LINKED ISSUE #940: Swiping back to 3p content reloads it
Steps to reproduce:

- Go to profile tab > Following
- Tap on a profile
- Tap on 3p note (A) (loads > displays)
- Tap on a link to some other note (B)
- Go back (B -> A)

Result: A is reloaded. Loading indicator also spins faster than usual, suggesting bug in animation code?

Expected: A should be the cached result from last load.

Defining the right behavior:

- We should only load read-only panels once at creation.
    - In future we could consider some sort of time-elapsed cache expiry
- Panel can be refreshed via pull-to-refresh.

This is similar to browser behavior with page loading.

### PR DESCRIPTION
**Pull request by bfollington**
Fixes #940 

Introduce new `MemoViewer` action `.refreshAll` that actually does the loading. `.appear` will only trigger loading if the address changes and the `MemoViewerDetailView` listens for `AppAction.succeedSyncSphereWithGateway` to trigger `.refreshAll`.

My thinking is that 3P content can only change after a sync, so that's the only explicit trigger we need.

### CODE REVIEW

File: xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift [hunk 1]
```diff
@@ -464,20 +472,45 @@ struct MemoViewerDetailModel: ModelProtocol {
         environment: Environment,
         description: MemoViewerDetailDescription
     ) -> Update<Self> {
+        guard state.address != description.address else {
+            logger.warning("Attempted to appear with same address, doing nothing")
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift:476]: Might be a bit noisy to log?

Comment (gordonbrander) [reply xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift:476]: `logger.log` seems more appropriate here, since this is expected behavior that is being handled gracefully.

File: xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift [hunk 2]
```diff
@@ -464,20 +472,45 @@ struct MemoViewerDetailModel: ModelProtocol {
...
+            environment: environment
+        )
+    }
+    
+    static func refreshAll(
+        state: Self,
+        environment: Environment
+    ) -> Update<Self> {
+        guard let address = state.address else {
+            logger.warning("Attempted to refresh with nil address")
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift:499]: `logger.log` seems more appropriate here, since this is expected behavior that is being handled gracefully.

**Review by gordonbrander — CHANGES_REQUESTED** [review]
Two suggestions, otherwise LGTM.

**Review by gordonbrander — APPROVED** [review]
LGTM assuming logging changes land
