### PR TITLE
Remodel User Profile sheets & alerts

### LINKED ISSUE #945: Following sheet has long delay before retracting
Steps to reproduce:

- Go to profile you don't follow
- Tap follow (follow sheet opens)
- Confirm follow

What happens: long delay without any feedback to user.

What should happen:

- Ideal: follow sheet should immediately retract. If failure occurs in the background, we should notify the user to try again. (This would require creating the toast component we've talked about).
- Satisfice: display some feedback to the user that follow is proceeding.

### PR DESCRIPTION
**Pull request by bfollington**
Fixes #945 

I originally tried an approach based on `.alert` here but decided after chatting to @gordonbrander to pivot to our own `Toast` notification system. 

I've implemented the MVP of a `ToastStack` with queued, expiring notifications, displayed one at a time. 

https://github.com/subconsciousnetwork/subconscious/assets/5009316/b41b80e7-02f2-4993-86f3-b8228cdfa215

### CODE REVIEW

File: xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift [hunk 1]
```diff
@@ -37,6 +39,25 @@ struct FollowNewUserFormSheetView: View {
...
+        send(.attemptFollow(did, name.toPetname()))
+    }
+    
+    func onCancel() { 
+        send(.dismissSheet)
+    }
+    
+//    func onDismissFailFollowError() {
+//        send(.dismissError)
+//    }
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift:59]: Drop

File: xcode/Subconscious/Shared/Components/Common/Profile/FollowUserViaQRCodeView.swift [hunk 2]
```diff
@@ -46,18 +46,18 @@ struct FollowUserViaQRCodeView: View {
...
+//                set: { _ in }
+//            )
+//        ) {
+//            let errorMessage = errorMessage ?? "Failed to scan"
+//            
+//            return Alert(
+//                title: Text("QR Code Error"),
+//                message: Text(errorMessage)
+//            )
+//        }
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Common/Profile/FollowUserViaQRCodeView.swift:61]: Uncomment!

File: xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift [hunk 3]
```diff
@@ -248,11 +248,30 @@ struct UserProfileView: View {
...
+                Alert(
+                    title: Text("Sumtin wong"),
+                    message: Text(state.presentedAlert?.error ?? "An unknown error ocurred"),
+                    primaryButton: .default(Text("Try Again"), action: {
+                        store.send(.presentFollowSheet(true))
+                    }),
+                    secondaryButton: .cancel(Text("Cancel"), action: {
+                        store.send(.dismissAlert)
+                    })
+                )
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift:272]: Implement actual Alert styles

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 4]
```diff
@@ -141,23 +171,24 @@ enum UserProfileDetailAction {
     case presentFollowNewUserFormSheet(Bool)
     case presentRenameSheet(Bool)
     
+    case presentAlert(UserProfileAlert)
+    case forcePresentAlert(Bool)
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:175]: Remove this concept, not needed

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 5]
```diff
@@ -312,15 +341,13 @@ struct UserProfileDetailModel: ModelProtocol {
     static let followingTabIndex: Int = 1
     
     var loadingState = LoadingState.loading
+    var isAlertPresented = false
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:344]: Remove this concept, not needed

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 6]
```diff
@@ -722,6 +743,43 @@ struct UserProfileDetailModel: ModelProtocol {
...
+        state: Self,
+        environment: Environment,
+        alert: UserProfileAlert
+    ) -> Update<Self> {
+        var model = state
+//        model.isRenameSheetPresented = false
+//        model.isFollowSheetPresented = false
+//        model.isUnfollowConfirmationPresented = false
+//        model.isFollowNewUserFormSheetPresented = false
+//        model.isMetaSheetPresented = false
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:756]: Drop

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 7]
```diff
@@ -722,6 +743,43 @@ struct UserProfileDetailModel: ModelProtocol {
...
+    
+    static func forcePresentAlert(
+        state: Self,
+        environment: Environment,
+        presented: Bool
+    ) -> Update<Self> {
+        var model = state
+        model.isAlertPresented = presented
+        return Update(state: model)
+    }
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:771]: Drop

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 8]
```diff
@@ -800,12 +858,26 @@ struct UserProfileDetailModel: ModelProtocol {
...
     ) -> Update<Self> {
         var model = state
-        model.failFollowErrorMessage = error
+        model.isFollowSheetPresented = false
+        model.isFollowNewUserFormSheetPresented = false
         
-        return Update(state: model)
+        // We must defer between dismissing the sheet and presenting the alert
+        // or else SwiftUI throws a tantrum and swallows the alert
+        let fx: Fx<UserProfileDetailAction> = Future.detached {
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:870]: Q: if we dismiss the sheet immediately when beginning the action, is this still necessary?

It is a footgun lying is wait regardless, but we can document the other dismissal sites.

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 9]
```diff
@@ -1128,24 +1182,30 @@ struct UserProfileDetailModel: ModelProtocol {
         )
     }
     
+    
+
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:1186]: whitespace

File: xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift [hunk 10]
```diff
@@ -121,12 +130,14 @@ struct FollowNewUserFormSheetView: View {
...
-            did: Did("did:key:123")!,
-            onAttemptFollow: {},
-            onCancel: {},
-            onDismissFailFollowError: {}
+            store: Store(
+                state: FollowNewUserFormSheetModel(),
+                environment: AppEnvironment()
+            ).viewStore(
+                get: { $0 },
+                tag: { $0 }
```
Comment (bfollington) [inline xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift:138]: Finally, a valid use for `$0`

File: xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift [hunk 11]
```diff
@@ -116,14 +116,15 @@ struct EditProfileSheetModel: ModelProtocol {
 
 
 struct EditProfileSheet: View {
-    var state: EditProfileSheetModel
-    var send: (EditProfileSheetAction) -> Void
+    var store: ViewStore<EditProfileSheetModel>
+    
+    var state: EditProfileSheetModel { store.state }
+    var send: (EditProfileSheetAction) -> Void { store.send }
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift:122]: Would prefer to reference these through `store.` It's easier to track intent in the view IMO.

File: xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift [hunk 12]
```diff
@@ -11,18 +11,20 @@ import ObservableStore
 import CodeScanner
 
 struct FollowNewUserFormSheetView: View {
-    var state: FollowNewUserFormSheetModel
+    var store: ViewStore<FollowNewUserFormSheetModel>
+    var did: Did?
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift:15]: We should get this value into `FollowNewUserFormSheetModel` somehow instead of having to thread in an additional value.

File: xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift [hunk 13]
```diff
@@ -11,18 +11,20 @@ import ObservableStore
...
+    
+    var state: FollowNewUserFormSheetModel {
+        store.state
+    }
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift:19]: Same as above, would prefer referencing store directly in view.

File: xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift [hunk 14]
```diff
@@ -11,18 +11,20 @@ import ObservableStore
...
-    
-    var did: Did?
-    
-    var onAttemptFollow: () -> Void
-    var onCancel: () -> Void
     
-    var onDismissFailFollowError: () -> Void
+    var send: (FollowNewUserFormSheetAction) -> Void {
+        store.send
+    }
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift:27]: Same as above. Would prefer referencing `store.send` directly in view.

File: xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift [hunk 15]
```diff
@@ -37,6 +39,21 @@ struct FollowNewUserFormSheetView: View {
         }
     }
     
+    func onAttemptFollow() {
+        guard let did = form.did.validated else {
+            return
+        }
+        guard let name = form.petname.validated else {
+            return
+        }
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift:48]: This logic should be handled in the update function.

File: xcode/Subconscious/Shared/Components/Common/Profile/FollowUserSheet.swift [hunk 16]
```diff
@@ -169,15 +169,14 @@ struct FollowUserSheetFormCursor: CursorProtocol {
 }
 
 struct FollowUserSheet: View {
-    var state: FollowUserSheetModel
-    var send: (FollowUserSheetAction) -> Void
+    var store: ViewStore<FollowUserSheetModel>
+   
+    var state: FollowUserSheetModel { store.state }
+    var send: (FollowUserSheetAction) -> Void { store.send }
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/FollowUserSheet.swift:175]: Same comments as above. Would prefer to reference store directly.

File: xcode/Subconscious/Shared/Components/Common/Profile/FollowUserSheet.swift [hunk 17]
```diff
@@ -169,15 +169,14 @@ struct FollowUserSheetFormCursor: CursorProtocol {
...
     
     var onAttemptFollow: () -> Void
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/FollowUserSheet.swift:177]: Now that we're bringing a viewstore into this view, we should not need callbacks, since we should handle via view store update function and `ViewStore.send()`

File: xcode/Subconscious/Shared/Components/Common/Profile/UserProfileSheets.swift [hunk 18]
```diff
@@ -35,8 +35,15 @@ struct MetaSheetModifier: ViewModifier {
...
-    let send: (UserProfileDetailAction) -> Void
+    @ObservedObject var store: Store<UserProfileDetailModel>
+    
+    var state: UserProfileDetailModel {
+        store.state
+    }
+    
+    var send: (UserProfileDetailAction) -> Void {
+        store.send
+    }
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/UserProfileSheets.swift:46]: Would prefer to reference directly

File: xcode/Subconscious/Shared/Components/Common/Profile/UserProfileSheets.swift [hunk 19]
```diff
@@ -64,19 +70,16 @@ struct FollowSheetModifier: ViewModifier {
...
             }
     }
 }
 
 struct RenameSheetModifier: ViewModifier {
-    let state: UserProfileDetailModel
-    let send: (UserProfileDetailAction) -> Void
+    @ObservedObject var store: Store<UserProfileDetailModel>
+    var state: UserProfileDetailModel { store.state }
+    var send: (UserProfileDetailAction) -> Void { store.send }
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/UserProfileSheets.swift:82]: Would prefer to reference directly

File: xcode/Subconscious/Shared/Components/Common/Profile/UserProfileSheets.swift [hunk 20]
```diff
@@ -219,39 +201,32 @@ struct EditProfileSheetModifier: ViewModifier {
...
-    let send: (UserProfileDetailAction) -> Void
+    @ObservedObject var store: Store<UserProfileDetailModel>
+    
+    var state: UserProfileDetailModel {
+        store.state
+    }
+    
+    var send: (UserProfileDetailAction) -> Void {
+        store.send
+    }
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/UserProfileSheets.swift:212]: Would prefer to reference directly.

File: xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift [hunk 21]
```diff
@@ -248,11 +248,10 @@ struct UserProfileView: View {
             }
         })
         .metaSheet(state: state, send: send)
-        .follow(state: state, send: send)
+        .follow(store: store)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift:251]: 🙌

File: xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift [hunk 22]
```diff
@@ -248,11 +248,10 @@ struct UserProfileView: View {
...
         .unfollow(state: state, send: send)
         .editProfile(app: app, store: store)
-        .followNewUser(state: state, send: send)
-        .rename(state: state, send: send)
+        .rename(store: store)
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift:254]: 🙌

File: xcode/Subconscious/Shared/Components/Common/Toast/ToastStackView.swift [hunk 23]
```diff
@@ -0,0 +1,131 @@
...
+    ) -> Update<Self> {
+        var model = state
+        model.stack.removeAll(where: { $0.id == toast.id })
+        
+        if let first = model.stack.first {
+            return update(
+                state: model,
+                action: .toastPresented(toast: first),
+                environment: environment
+            )
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Toast/ToastStackView.swift:109]: It might be worth returning this as an `fx` so we see the `.toastPresented()` show up in the logs.

```swift
let fx: Fx<ToastStackAction> = Just(.toastPresented(toast: first)).eraseToAnyPublisher()
return Update(state: model, fx: fx)
```

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 24]
```diff
@@ -78,6 +78,14 @@ extension UserProfileDetailAction {
...
         case let .succeedUnfollow(identity, petname):
             return .notifySucceedUnfollow(identity: identity, petname: petname)
+        case .failRename:
+            return AppAction.pushToast(message: "Failed to rename user")
+        case .failUnfollow:
+            return AppAction.pushToast(message: "Failed to unfollow user")
+        case .failEditProfile:
+            return AppAction.pushToast(message: "Failed to edit profile")
+        case .failFollow:
+            return AppAction.pushToast(message: "Failed to follow user")
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:88]: I think we need to localize these strings with `String(localized:)`

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift [hunk 25]
```diff
@@ -754,20 +728,21 @@ struct UserProfileDetailModel: ModelProtocol {
...
-                    return .failFollowDueToPetnameCollision(
-                        petname: petname
-                    )
-                case _:
-                    return .failFollow(
-                        error: error.localizedDescription
-                    )
-                }
+                .failFollow(
+                    error: error.localizedDescription
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:732]: If we're presenting the `localizedDescription` to users, we may want to do a pass on the errors that could happen here and make them user-friendly.

**Review by gordonbrander — CHANGES_REQUESTED** [review]
Thanks, this is going to be a huge improvement!

A few changes requested.

I'd also like to do a follow-up design pass on the toasts in Figma.

- Shadow and FAB shadow bleed over in odd ways. Perhaps we just make toasts big enough to cover the FAB shadow?
- I'd like to explore a visual direction where the toasts have a fill. Perhaps the toast might be Subconscious grey `#DFDBEB`, blush `#EDCFEA` or purple `#C570DB`?

File: xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift (hunk 25 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift:774]: Currently we're swallowing them and presenting generic errors instead (see `UserProfileDetailAction.toAppAction`).

I don't think there's much benefit in surfacing Noosphere errors to the user?

**Comment by bfollington** [comment]
All previous feedback has been actioned.

I kept tugging on the thread here and ended up refactoring quite a bit more. Managed to eliminate all the sidechannel communication using callbacks and migrate all the user profile sheets to `ViewStore`. I also ended up migrating every form field to `ViewStore` at the same time.

Apologies for the massive diff, not that much has actually changed but I've broken everything into modules which creates a large delta.

**Comment by bfollington** [comment]
> Thanks, this is going to be a huge improvement!
> 
> A few changes requested.
> 
> I'd also like to do a follow-up PR + design pass on the toasts in Figma.
> 
> * Shadow and FAB shadow bleed over in odd ways. Perhaps we just make toasts big enough to cover the FAB shadow?
> * I'd like to explore a visual direction where the toasts have a fill. Perhaps the toast might be Subconscious grey `#DFDBEB`, blush `#EDCFEA` or purple `#C570DB`?

Got an issue to track this here: https://github.com/subconsciousnetwork/subconscious/issues/988

File: xcode/Subconscious/Shared/Components/Common/Profile/Sheets/EditProfileSheet.swift [hunk 26]
```diff
@@ -110,42 +120,42 @@ struct EditProfileSheetModel: ModelProtocol {
...
 struct EditProfileSheet: View {
-    var state: EditProfileSheetModel
-    var send: (EditProfileSheetAction) -> Void
-    var user: UserProfile
-    var statistics: UserProfileStatistics?
-    var failEditProfileMessage: String?
-    var onEditProfile: () -> Void
-    var onCancel: () -> Void
-    var onDismissError: () -> Void
+    var store: ViewStore<EditProfileSheetModel>
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/Sheets/EditProfileSheet.swift:133]: A dozen properties becomes one ViewStore. You love to see it.

File: xcode/Subconscious/Shared/Components/Common/Profile/Sheets/EditProfileSheetModifier.swift [hunk 27]
```diff
@@ -0,0 +1,55 @@
...
+                        case .success(let peer) where peer.identity == store.state.user?.did:
+                            return true
+                        default:
+                            return false
+                        }
+                    }):
+                    
+                    store.send(.refresh(forceSync: false))
+                    break
+                case _:
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/Sheets/EditProfileSheetModifier.swift:50]: Nit: prefer `default`.

File: xcode/Subconscious/Shared/Components/Common/Profile/Sheets/EditProfileSheetModifier.swift [hunk 28]
```diff
@@ -0,0 +1,55 @@
...
+                case .completeIndexPeers(let results)
+                    // Only refresh the view if the presented user was indexed
+                    where results.contains(where: { result in
+                        switch (result) {
+                        case .success(let peer) where peer.identity == store.state.user?.did:
+                            return true
+                        default:
+                            return false
+                        }
+                    }):
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/Sheets/EditProfileSheetModifier.swift:46]: This business logic should be handled in a `store` `completeIndexPeers` update function. Do the `contains` logic in there, and no-op if it doesn't match, otherwise return `update(state: state, .refresh(forceSync:false)`.

That way we get a testable update function.

File: xcode/Subconscious/Shared/Components/Common/Profile/Sheets/FollowUserSheet.swift [hunk 29]
```diff
@@ -214,27 +220,16 @@ struct FollowUserSheet: View {
                 }
                 
                 Button(
-                    action: onAttemptFollow,
+                    action: { store.send(.submit) },
```
Comment (gordonbrander) [inline xcode/Subconscious/Shared/Components/Common/Profile/Sheets/FollowUserSheet.swift:223]: 👍 I like directly calling send. Easier to trace where messages originate.

**Review by gordonbrander — CHANGES_REQUESTED** [review]
Small changes requested. Otherwise, looks great.

File: xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift [hunk 30]
```diff
@@ -15,8 +15,10 @@ struct ValidatedFormField<Output: Equatable>: View {
     
     var alignment: HorizontalAlignment = .leading
     var placeholder: String
-    var field: FormField<String, Output>
-    var send: (FormFieldAction<String>) -> Void
+    var field: ViewStore<FormField<String, Output>>
+    
+//    var field: FormField<String, Output>
+//    var send: (FormFieldAction<String>) -> Void
```
[the remark this answers is not in the document]
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift:21]: Good catch, thanks!

File: xcode/Subconscious/Shared/Library/StoreUtilities.swift [hunk 31]
```diff
@@ -0,0 +1,16 @@
...
+//
+//  Created by Ben Follington on 3/11/2023.
+//
+
+import Foundation
+import ObservableStore
+
+extension Store where Model : ModelProtocol {
+    /// Utility method to turn a store into a  ViewStore, intended for use in SwiftUI previews.
+    func toViewStore() -> ViewStore<Model> {
```
[the remark this answers is not in the document]
Comment (bfollington) [reply xcode/Subconscious/Shared/Library/StoreUtilities.swift:13]: Qualified the name further to make it clear(er) 😬: `toViewStoreForSwiftUIPreview`

File: xcode/Subconscious/Shared/Components/Common/Profile/Sheets/EditProfileSheetModifier.swift (hunk 28 above)
Comment (bfollington) [reply xcode/Subconscious/Shared/Components/Common/Profile/Sheets/EditProfileSheetModifier.swift:46]: Turns out this is stale / deprecated code and we already moved the logic into `UserProfileDetailModel.completeIndexPeers`, deleted.

**Review by gordonbrander — APPROVED** [review]
LGTM
